### ISSUE TITLE
Grunt or Gulp support

### ISSUE THREAD

**Issue by dinever** [720kb/hubuntu-ui#11]
It would be great if we add Grunt or Gulp support for hubuntu-ui to automate various tasks.

**Comment by 45kb** [comment]
Hi @dinever, you're right, i agree it is important.
We will add it as soon as possible!

Gulp btw :)

**Comment by 45kb** [comment]
shipped https://github.com/720kb/hubuntu-ui#run-it

Thank you for the suggestion :+1:
